import streamlit as st
import ollama



# PAGE SETTINGS


# Configure the basic settings of the Streamlit page
st.set_page_config(
    page_title="AI",          # Title shown on the browser tab
    page_icon="🤖",           # Icon shown on the browser tab
    layout="centered"         # Keep the app content centered
)



# TITLE AND DESCRIPTION


# Display the main title of the application
st.title("🤖 THE ULTIMATE")

# Display a short description below the title
st.write("Ask anything and get an answer.")


# USER INPUT


# Create a text input box to get a question from the user
prompt = st.text_input(
    "💬 Enter your question",              # Label of the input box
    placeholder="e.g. WHO AM I ?"          # Example text shown inside the input box
)


# ASK AI BUTTON

# Create an "Ask AI" button
# use_container_width=True makes the button use the available width
if st.button("🚀 Ask AI", use_container_width=True):

    # Check whether the user has entered a question
    # strip() removes unnecessary spaces from the beginning and end
    if prompt.strip():

        # Show a loading message while the AI is generating a response
        with st.spinner("🤔 AI is thinking..."):

            # Send the user's question to the Ollama AI model
            response = ollama.chat(

                # Specify which Ollama model should be used
                model="qwen2.5:0.5b",

                # Send the user's message to the model
                messages=[
                    {
                        # Define the sender of the message
                        "role": "user",

                        # Pass the user's question as the message content
                        "content": prompt
                    }
                ]
            )


        # DISPLAY AI RESPONSE


        # Display a subheading for the AI response
        st.subheader("🤖 AI Response")

        # Extract and display the actual response generated by the AI
        st.write(response["message"]["content"])


    # If the user did not enter any question
    else:

        # Display a warning message
        st.warning("⚠️ Please enter a question first.")